name: Build and Deploy to Azure Container App

on:
  push:
    branches:
      - main

env:
  ACR_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  RESOURCE_GROUP: lrscard-currencyservice
  CONTAINER_APP_NAME: lrscard-currencyservice-api
  IMAGE_NAME: lrscurrencyserviceapi

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set version tag
        id: vars
        run: |
          echo "DATE_TAG=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo "REV=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Docker Login to ACR
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -f ./src/LRSCard.CurrencyService.API/Dockerfile \
          -t $ACR_SERVER/$IMAGE_NAME:latest \
          ./src
          docker push $ACR_SERVER/$IMAGE_NAME:latest

      - name: Deploy to Azure Container App
        run: |
            az containerapp update \
              --name lrscard-currencyservice-api \
              --resource-group lrscard-currencyservice \
              --image lrscardcurrencyserviceacr-cwf3fpcnfze9akbe.azurecr.io/lrscurrencyserviceapi:latest
